### PR TITLE
remove plugin-auth-backend-module-guest-provider

### PR DESCRIPTION
**Pull request by jessesanford**
Removing guest login temporarily due to: https://github.com/backstage/backstage/issues/24284 which is fixed in: https://github.com/backstage/backstage/pull/26655 but has not yet been cut into a release

### CODE REVIEW

**Comment by nabuskey** [comment]
With the change in oauth provider in backstage, we also need to remove the scope field. This should have been done previously tbh. Hadn't had the time to take care of it

```bash
ubuntu@ip-10-192-11-119:~/stacks$ git diff
diff --git a/ref-implementation/backstage/manifests/install.yaml b/ref-implementation/backstage/manifests/install.yaml
index 969bf39..dfe4ebd 100644
--- a/ref-implementation/backstage/manifests/install.yaml
+++ b/ref-implementation/backstage/manifests/install.yaml
@@ -148,7 +148,6 @@ data:
             metadataUrl: ${KEYCLOAK_NAME_METADATA}
             clientId: backstage
             clientSecret: ${KEYCLOAK_CLIENT_SECRET}
-            scope: 'openid profile email groups'
             prompt: auto

     scaffolder:
@@ -264,7 +263,7 @@ spec:
                 name: gitea-credentials
             - secretRef:
                 name: argocd-credentials
-          image: ghcr.io/cnoe-io/backstage-app:b8e4f08914af17a48ed6b8b83a3621a9f4b4181d
+          image: ghcr.io/cnoe-io/backstage-app:f8b92b5067803554a4891fccd399326ac16db558
           name: backstage
           ports:
             - containerPort: 7007
```

**Comment by Rugvip** [comment]
The fix for this will be released tomorrow, so might be best to skip this at this point

**Comment by jessesanford** [comment]
> The fix for this will be released tomorrow, so might be best to skip this at this point

Any chance you can link to the release notes or a link that shows the fix being added? It will help when folks find this issue from google or when we need to debug why things still aren't working after updating.

**Comment by nabuskey** [comment]
https://github.com/backstage/backstage/pull/26655#issuecomment-2346654203

Sounds like it's coming out today.

**Comment by Rugvip** [comment]
Yep, 1.31 is now out with a fix: https://backstage.io/docs/releases/v1.31.0#guest-auth-no-longer-halting-production-startup

**Pull request closed without merging**
